### ISSUE TITLE
smpl_link error while duplicating 

### ISSUE THREAD

**Issue by yosun** [hongfz16/EVA3D#25]
What is the smpl_link parameter for duplicating the HF space?

also your huggingface space is down

https://huggingface.co/spaces/hongfz16/EVA3D

```
Runtime error
00/160M [00:00<?, ?B/s][A

  0%|          | 0.00/160M [00:00<?, ?B/s][A

  0%|          | 0.00/160M [00:00<?, ?B/s][ATraceback (most recent call last):
  File "app.py", line 42, in download_pretrained_models
    download_file(session, eva3d_deepfashion_model)
  File "EVA3D/download_models.py", line 81, in download_file
    res.raise_for_status()
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://drive.google.com/uc?id=1SYPjxnHz3XPRhTarx_Lw8SG_iz16QUMU&confirm=t&uuid=3a51e74f-d6cd-4692-adcd-867a1dde7a18

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 56, in <module>
    download_pretrained_models()
  File "app.py", line 46, in download_pretrained_models
    download_file(session, eva3d_deepfashion_model, use_alt_url=True)
  File "EVA3D/download_models.py", line 80, in download_file
    with session.get(file_url, stream=True) as res:
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?

  0%|          | 0.00/160M [00:00<?, ?B/s]

  0%|          | 0.00/160M [00:00<?, ?B/s]
Container logs:

Cloning into 'EVA3D'...
Collecting fvcore
  Downloading fvcore-0.1.5.post20221221.tar.gz (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 721.9 kB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: plotly in /home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages (5.13.1)
Collecting plotly
  Downloading plotly-5.15.0-py2.py3-none-any.whl (15.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.5/15.5 MB 32.9 MB/s eta 0:00:00
Requirement already satisfied: numpy in /home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from fvcore) (1.21.2)
Collecting yacs>=0.1.6
  Downloading yacs-0.1.8-py3-none-any.whl (14 kB)
Requirement already satisfied: pyyaml>=5.1 in /home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from fvcore) (6.0)
Requirement already satisfied: tqdm in /home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from fvcore) (4.64.1)
Collecting termcolor>=1.1
  Downloading termcolor-2.3.0-py3-none-any.whl (6.9 kB)
Requirement already satisfied: Pillow in /home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from fvcore) (9.0.1)
Collecting tabulate
  Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
Collecting iopath>=0.1.7
  Downloading iopath-0.1.10.tar.gz (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.2/42.2 kB 760.8 kB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: tenacity>=6.2.0 in /home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from plotly) (8.2.2)
Requirement already satisfied: packaging in /home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from plotly) (23.0)
Requirement already satisfied: typing_extensions in /home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from iopath>=0.1.7->fvcore) (4.5.0)
Collecting portalocker
  Downloading portalocker-2.7.0-py2.py3-none-any.whl (15 kB)
Building wheels for collected packages: fvcore, iopath
  Building wheel for fvcore (setup.py): started
  Building wheel for fvcore (setup.py): finished with status 'done'
  Created wheel for fvcore: filename=fvcore-0.1.5.post20221221-py3-none-any.whl size=61405 sha256=585e93d8432e05cf12db25b5afcdc7f126e03ac93b73784ce8d2ca21064f083a
  Stored in directory: /home/user/.cache/pip/wheels/6d/1f/39/577cab48487ad5c31acd046ee33dea7ca6fede7e923b2a2bc1
  Building wheel for iopath (setup.py): started
  Building wheel for iopath (setup.py): finished with status 'done'
  Created wheel for iopath: filename=iopath-0.1.10-py3-none-any.whl size=31532 sha256=0b594ceaf50d8e5be928e2a127ebdfd67283cf96ada1d623d808621c3e253cc9
  Stored in directory: /home/user/.cache/pip/wheels/85/e6/c8/4a67ea2cd453fd2e02c616b615fe8655ae67246c8e669bd464
Successfully built fvcore iopath
Installing collected packages: yacs, termcolor, tabulate, portalocker, plotly, iopath, fvcore
  Attempting uninstall: plotly
    Found existing installation: plotly 5.13.1
    Uninstalling plotly-5.13.1:
      Successfully uninstalled plotly-5.13.1
Successfully installed fvcore-0.1.5.post20221221 iopath-0.1.10 plotly-5.15.0 portalocker-2.7.0 tabulate-0.9.0 termcolor-2.3.0 yacs-0.1.8

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
Looking in links: https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu116_pyt1131/download.html
Collecting pytorch3d
  Downloading https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu116_pyt1131/pytorch3d-0.7.2-cp38-cp38-linux_x86_64.whl (72.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.8/72.8 MB 258.8 MB/s eta 0:00:00
Requirement already satisfied: iopath in /home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from pytorch3d) (0.1.10)
Requirement already satisfied: fvcore in /home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from pytorch3d) (0.1.5.post20221221)
Requirement already satisfied: tabulate in /home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from fvcore->pytorch3d) (0.9.0)
Requirement already satisfied: termcolor>=1.1 in /home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from fvcore->pytorch3d) (2.3.0)
Requirement already satisfied: pyyaml>=5.1 in /home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from fvcore->pytorch3d) (6.0)
Requirement already satisfied: yacs>=0.1.6 in /home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from fvcore->pytorch3d) (0.1.8)
Requirement already satisfied: tqdm in /home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from fvcore->pytorch3d) (4.64.1)
Requirement already satisfied: numpy in /home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from fvcore->pytorch3d) (1.21.2)
Requirement already satisfied: Pillow in /home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from fvcore->pytorch3d) (9.0.1)
Requirement already satisfied: portalocker in /home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from iopath->pytorch3d) (2.7.0)
Requirement already satisfied: typing-extensions in /home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages (from iopath->pytorch3d) (4.5.0)
Installing collected packages: pytorch3d
Successfully installed pytorch3d-0.7.2
Downloading EVA3D model pretrained on DeepFashion.
Google Drive download failed.
Trying do download from alternate server

  0%|          | 0.00/160M [00:00<?, ?B/s]
  0%|          | 0.00/160M [00:00<?, ?B/s]
  0%|          | 2.26k/160M [00:00<3:26:04, 13.0kB/s]
  0%|          | 0.00/160M [00:00<?, ?B/s]           
  0%|          | 0.00/160M [00:00<?, ?B/s]
  0%|          | 0.00/160M [00:00<?, ?B/s]
  0%|          | 0.00/160M [00:00<?, ?B/s]
  0%|          | 0.00/160M [00:00<?, ?B/s]
  0%|          | 0.00/160M [00:00<?, ?B/s]
  0%|          | 0.00/160M [00:00<?, ?B/s]
  0%|          | 0.00/160M [00:00<?, ?B/s]
  0%|          | 0.00/160M [00:00<?, ?B/s]

  0%|          | 0.00/160M [00:00<?, ?B/s]

  0%|          | 0.00/160M [00:00<?, ?B/s]

  0%|          | 0.00/160M [00:00<?, ?B/s]

  0%|          | 0.00/160M [00:00<?, ?B/s]

  0%|          | 0.00/160M [00:00<?, ?B/s]

  0%|          | 0.00/160M [00:00<?, ?B/s]

  0%|          | 0.00/160M [00:00<?, ?B/s]

  0%|          | 0.00/160M [00:00<?, ?B/s]

  0%|          | 0.00/160M [00:00<?, ?B/s]

  0%|          | 0.00/160M [00:00<?, ?B/s]

  0%|          | 0.00/160M [00:00<?, ?B/s]Traceback (most recent call last):
  File "app.py", line 42, in download_pretrained_models
    download_file(session, eva3d_deepfashion_model)
  File "EVA3D/download_models.py", line 81, in download_file
    res.raise_for_status()
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://drive.google.com/uc?id=1SYPjxnHz3XPRhTarx_Lw8SG_iz16QUMU&confirm=t&uuid=3a51e74f-d6cd-4692-adcd-867a1dde7a18

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 56, in <module>
    download_pretrained_models()
  File "app.py", line 46, in download_pretrained_models
    download_file(session, eva3d_deepfashion_model, use_alt_url=True)
  File "EVA3D/download_models.py", line 80, in download_file
    with session.get(file_url, stream=True) as res:
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?

  0%|          | 0.00/160M [00:00<?, ?B/s]

  0%|          | 0.00/160M [00:00<?, ?B/s]
```

**Comment by hongfz16** [comment]
Hi. Thank you for the kind reminder! Unfortunately, we are not allowed to further distribute the SMPL model. Please register [here](https://smpl.is.tue.mpg.de/) and download it.

**Comment by yosun** [comment]
Thanks for checking up on issues - which SMPL model does your HF repo use?

**Comment by yosun** [comment]
Can you modify your HF example to also accept a RGB image as input via
API?  (Not just randomized input)
